# generated by wxGlade HG on Sat Nov 19 19:24:45 2011
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package MainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MainFrame::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{notebook} = Wx::Notebook->new($self, -1, wxDefaultPosition, wxDefaultSize, 0);
	$self->{tabLang} = Wx::Panel->new($self->{notebook}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{tabCateg} = Wx::Panel->new($self->{notebook}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{sizer_3_staticbox} = Wx::StaticBox->new($self->{tabLang}, -1, "" );
	$self->{sizer_c11_staticbox} = Wx::StaticBox->new($self->{tabCateg}, -1, "" );
	$self->{tabBlog} = Wx::Panel->new($self->{notebook}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{label_1} = Wx::StaticText->new($self->{tabCateg}, -1, "Name: ", wxDefaultPosition, wxDefaultSize, );
	$self->{text_ctrl_2} = Wx::TextCtrl->new($self->{tabCateg}, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{button_1} = Wx::Button->new($self->{tabCateg}, -1, "Crear");
	$self->{button_2} = Wx::Button->new($self->{tabCateg}, -1, "Modificar");
	$self->{button_3} = Wx::Button->new($self->{tabCateg}, -1, "Eliminar");
	$self->{button_4} = Wx::Button->new($self->{tabCateg}, -1, "Actualizar");
	$self->{grid_2} = Wx::Grid->new($self->{tabCateg}, -1);
	$self->{labelNameLang} = Wx::StaticText->new($self->{tabLang}, -1, "Idioma: ", wxDefaultPosition, wxDefaultSize, );
	$self->{text_ctrl_1} = Wx::TextCtrl->new($self->{tabLang}, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{grid_1} = Wx::Grid->new($self->{tabLang}, -1);

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MainFrame::__set_properties

	$self->SetTitle("wxPerlBlog");
	my $icon = Wx::Icon->new();
	$icon->CopyFromBitmap(Wx::Bitmap->new("/home/cgc/Documents/wxPerlBlog/usr/icon.png", wxBITMAP_TYPE_ANY));
	$self->SetIcon($icon);
	$self->SetSize(Wx::Size->new(600, 440));
	$self->{grid_2}->CreateGrid(10, 3);
	$self->{grid_2}->SetSelectionMode(wxGridSelectCells);
	$self->{grid_1}->CreateGrid(10, 3);
	$self->{grid_1}->SetSelectionMode(wxGridSelectCells);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MainFrame::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{grid_sizer_1} = Wx::FlexGridSizer->new(3, 3, 7, 8);
	$self->{sizer_3}= Wx::StaticBoxSizer->new($self->{sizer_3_staticbox}, wxHORIZONTAL);
	$self->{from_sizer_2} = Wx::FlexGridSizer->new(5, 5, 0, 0);
	$self->{grid_sizer_c1} = Wx::FlexGridSizer->new(5, 3, 0, 0);
	$self->{sizer_c11}= Wx::StaticBoxSizer->new($self->{sizer_c11_staticbox}, wxHORIZONTAL);
	$self->{grid_sizer_c111} = Wx::FlexGridSizer->new(5, 3, 0, 0);
	$self->{sizer_c1112} = Wx::FlexGridSizer->new(1, 7, 0, 0);
	$self->{grid_sizer_c1111} = Wx::FlexGridSizer->new(1, 3, 0, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 17, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1111}->Add($self->{label_1}, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1111}->Add(6, 6, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1111}->Add($self->{text_ctrl_2}, 0, wxEXPAND, 0);
	$self->{grid_sizer_c1111}->AddGrowableCol(2);
	$self->{grid_sizer_c111}->Add($self->{grid_sizer_c1111}, 1, wxEXPAND, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 12, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{sizer_c1112}->Add($self->{button_1}, 0, wxALIGN_RIGHT, 0);
	$self->{sizer_c1112}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{sizer_c1112}->Add($self->{button_2}, 0, wxALIGN_RIGHT, 0);
	$self->{sizer_c1112}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{sizer_c1112}->Add($self->{button_3}, 0, wxALIGN_RIGHT, 0);
	$self->{sizer_c1112}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{sizer_c1112}->Add($self->{button_4}, 0, wxALIGN_RIGHT, 0);
	$self->{grid_sizer_c111}->Add($self->{sizer_c1112}, 1, wxALIGN_RIGHT, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 8, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c111}->AddGrowableCol(1);
	$self->{sizer_c11}->Add($self->{grid_sizer_c111}, 1, wxEXPAND, 0);
	$self->{grid_sizer_c1}->Add($self->{sizer_c11}, 1, wxEXPAND, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 8, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add($self->{grid_2}, 1, wxEXPAND, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_c1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{tabCateg}->SetSizer($self->{grid_sizer_c1});
	$self->{grid_sizer_c1}->AddGrowableRow(3);
	$self->{grid_sizer_c1}->AddGrowableCol(1);
	$self->{grid_sizer_1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{from_sizer_2}->Add($self->{labelNameLang}, 0, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
	$self->{from_sizer_2}->Add($self->{text_ctrl_1}, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
	$self->{from_sizer_2}->AddGrowableCol(3);
	$self->{sizer_3}->Add($self->{from_sizer_2}, 1, wxEXPAND, 0);
	$self->{grid_sizer_1}->Add($self->{sizer_3}, 1, wxEXPAND, 0);
	$self->{grid_sizer_1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_1}->Add($self->{grid_1}, 1, wxEXPAND, 0);
	$self->{grid_sizer_1}->Add(4, 4, 0, wxADJUST_MINSIZE, 0);
	$self->{tabLang}->SetSizer($self->{grid_sizer_1});
	$self->{grid_sizer_1}->AddGrowableRow(2);
	$self->{grid_sizer_1}->AddGrowableCol(1);
	$self->{notebook}->AddPage($self->{tabBlog}, "Blogs");
	$self->{notebook}->AddPage($self->{tabCateg}, "Categorias");
	$self->{notebook}->AddPage($self->{tabLang}, "Idiomas");
	$self->{sizer_1}->Add($self->{notebook}, 1, wxEXPAND, 0);
	$self->SetSizer($self->{sizer_1});
	$self->Layout();
	$self->Centre();

# end wxGlade
}

# end of class MainFrame

1;

